"""
universe.py — AlphaVault Quant v1.0
Univers mondial : ~907 symboles + mapping secteurs.
Utilisé par trading_agent.py v2.1 + settings.py v2.2.
"""
from typing import List, Dict

_SECTOR_MAP: Dict[str, str] = {
    "AAPL":"Technology","MSFT":"Technology","NVDA":"Technology","AMD":"Technology",
    "INTC":"Technology","QCOM":"Technology","TXN":"Technology","AVGO":"Technology",
    "ORCL":"Technology","TSM":"Technology","ASML":"Technology","AMAT":"Technology",
    "MU":"Technology","ADI":"Technology","KLAC":"Technology","LRCX":"Technology",
    "CRM":"Technology","ADBE":"Technology","NOW":"Technology","INTU":"Technology",
    "ANSS":"Technology","CDNS":"Technology","SNPS":"Technology","CTSH":"Technology",
    "PLTR":"Technology","CRWD":"Technology","NET":"Technology","SNOW":"Technology",
    "DDOG":"Technology","PANW":"Technology","ZS":"Technology","FTNT":"Technology",
    "CYBR":"Technology","OKTA":"Technology","TWLO":"Technology","MDB":"Technology",
    "HUBS":"Technology","VEEV":"Technology","WDAY":"Technology","ZM":"Technology",
    "DOCU":"Technology","SPLK":"Technology","DT":"Technology","AI":"Technology",
    "JPM":"Finance","BAC":"Finance","GS":"Finance","MS":"Finance","C":"Finance",
    "WFC":"Finance","V":"Finance","MA":"Finance","AXP":"Finance","BLK":"Finance",
    "SCHW":"Finance","CB":"Finance","MMC":"Finance","AON":"Finance","TRV":"Finance",
    "PGR":"Finance","ALL":"Finance","MET":"Finance","PRU":"Finance","HIG":"Finance",
    "SOFI":"Fintech","AFRM":"Fintech","UPST":"Fintech","NU":"Fintech",
    "COIN":"Crypto","MARA":"Crypto","RIOT":"Crypto","IBIT":"Crypto","GBTC":"Crypto",
    "JNJ":"Healthcare","UNH":"Healthcare","LLY":"Healthcare","ABBV":"Healthcare",
    "PFE":"Healthcare","MRK":"Healthcare","TMO":"Healthcare","DHR":"Healthcare",
    "ABT":"Healthcare","AMGN":"Healthcare","GILD":"Healthcare","BIIB":"Healthcare",
    "REGN":"Healthcare","VRTX":"Healthcare","ISRG":"Healthcare","SYK":"Healthcare",
    "BSX":"Healthcare","MDT":"Healthcare","MRNA":"Healthcare","BNTX":"Healthcare",
    "XOM":"Energy","CVX":"Energy","COP":"Energy","SLB":"Energy","EOG":"Energy",
    "PXD":"Energy","MPC":"Energy","VLO":"Energy","PSX":"Energy","OXY":"Energy",
    "HAL":"Energy","BKR":"Energy","DVN":"Energy","FANG":"Energy","APA":"Energy",
    "HD":"Consumer Disc","MCD":"Consumer Disc","NKE":"Consumer Disc",
    "SBUX":"Consumer Disc","TGT":"Consumer Disc","LOW":"Consumer Disc",
    "BKNG":"Consumer Disc","ABNB":"Consumer Disc","TJX":"Consumer Disc",
    "ROST":"Consumer Disc","YUM":"Consumer Disc","CMG":"Consumer Disc",
    "GM":"Consumer Disc","F":"Consumer Disc","RIVN":"Consumer Disc",
    "WMT":"Consumer Staples","COST":"Consumer Staples","PG":"Consumer Staples",
    "KO":"Consumer Staples","PEP":"Consumer Staples","PM":"Consumer Staples",
    "MO":"Consumer Staples","CL":"Consumer Staples","EL":"Consumer Staples",
    "GE":"Industrials","CAT":"Industrials","DE":"Industrials","HON":"Industrials",
    "UNP":"Industrials","UPS":"Industrials","FDX":"Industrials","LMT":"Industrials",
    "RTX":"Industrials","NOC":"Industrials","GD":"Industrials","BA":"Industrials",
    "MMM":"Industrials","EMR":"Industrials","ETN":"Industrials","PH":"Industrials",
    "LIN":"Materials","APD":"Materials","SHW":"Materials","FCX":"Materials",
    "NEM":"Materials","NUE":"Materials","VMC":"Materials","ALB":"Materials",
    "NEE":"Utilities","DUK":"Utilities","SO":"Utilities","D":"Utilities",
    "AEP":"Utilities","EXC":"Utilities","XEL":"Utilities","AWK":"Utilities",
    "O":"REITs","SPG":"REITs","PLD":"REITs","AMT":"REITs","CCI":"REITs",
    "EQIX":"REITs","DLR":"REITs","PSA":"REITs","EQR":"REITs","AVB":"REITs",
    "META":"Communication","NFLX":"Communication","DIS":"Communication",
    "CMCSA":"Communication","T":"Communication","VZ":"Communication",
    "TMUS":"Communication","CHTR":"Communication",
    "SPY":"ETF","QQQ":"ETF","IWM":"ETF","DIA":"ETF","MDY":"ETF","VTI":"ETF",
    "VOO":"ETF","GLD":"ETF","SLV":"ETF","TLT":"ETF","IEF":"ETF","HYG":"ETF",
    "GDX":"ETF","USO":"ETF","LQD":"ETF","BND":"ETF","SHY":"ETF","AGG":"ETF",
    "XLK":"ETF","XLF":"ETF","XLV":"ETF","XLE":"ETF","XLY":"ETF","XLP":"ETF",
    "XLI":"ETF","XLB":"ETF","XLU":"ETF","XLRE":"ETF","XLC":"ETF",
    "EWJ":"ETF Intl","EWG":"ETF Intl","EWQ":"ETF Intl","EWU":"ETF Intl",
    "EWL":"ETF Intl","EWI":"ETF Intl","EWP":"ETF Intl","EWN":"ETF Intl",
    "EWD":"ETF Intl","FXI":"ETF Intl","KWEB":"ETF Intl","EWT":"ETF Intl",
    "EWY":"ETF Intl","EWA":"ETF Intl","EWH":"ETF Intl","EWS":"ETF Intl",
    "EPI":"ETF Intl","INDA":"ETF Intl","EWZ":"ETF Intl","EWC":"ETF Intl",
    "EWW":"ETF Intl","EZA":"ETF Intl","EEM":"ETF Intl","VEA":"ETF Intl",
    "VWO":"ETF Intl","IEFA":"ETF Intl","IEMG":"ETF Intl","ACWI":"ETF Intl",
    "KSA":"ETF Intl","UAE":"ETF Intl","GULF":"ETF Intl","AFK":"ETF Intl",
    "BABA":"China Tech","JD":"China Tech","PDD":"China Tech","NTES":"China Tech",
    "BIDU":"China Tech","NIO":"China Tech","XPEV":"China Tech","LI":"China Tech",
    "BILI":"China Tech","TME":"China Tech","IQ":"China Tech",
    "GRAB":"EM Tech","SEA":"EM Tech","SHOP":"EM Tech","MELI":"EM Tech",
}

def get_sector(symbol: str) -> str:
    return _SECTOR_MAP.get(symbol, _SECTOR_MAP.get(symbol.upper(), "Other"))

_FULL_UNIVERSE: List[str] = [
    "SPY","QQQ","IWM","DIA","MDY","VTI","VOO","VTV","VUG","VNQ",
    "XLK","XLF","XLV","XLE","XLY","XLP","XLI","XLB","XLU","XLRE","XLC",
    "GDX","GLD","SLV","USO","UNG","TLT","IEF","SHY","HYG","LQD","BND","AGG",
    "AAPL","MSFT","NVDA","GOOGL","GOOG","META","AMZN","TSLA","BRK-B",
    "AMD","AVGO","ORCL","INTC","QCOM","TXN","MU","ADI","AMAT","LRCX","KLAC",
    "ASML","TSM","MCHP","MPWR","ENPH","FSLR","SEDG","RUN","PLUG",
    "CRM","ADBE","NOW","INTU","ANSS","CDNS","SNPS","CTSH","EPAM",
    "PLTR","CRWD","NET","SNOW","DDOG","PANW","ZS","FTNT","CYBR","OKTA",
    "TWLO","MDB","HUBS","VEEV","WDAY","ZM","DOCU","SPLK","DT","AI",
    "JPM","BAC","GS","MS","V","MA","C","WFC","AXP","BLK","SCHW",
    "CB","MMC","AON","TRV","PGR","ALL","MET","PRU","HIG",
    "SOFI","AFRM","UPST","NU","COIN","HOOD","SQ","PYPL",
    "JNJ","UNH","LLY","ABBV","PFE","MRK","TMO","DHR","ABT","AMGN",
    "GILD","BIIB","REGN","VRTX","ISRG","SYK","BSX","MDT",
    "MRNA","BNTX","NVAX","CVS","WBA","HUM","ELV","CNC","CI",
    "XOM","CVX","COP","SLB","EOG","PXD","MPC","VLO","PSX","OXY",
    "HAL","BKR","DVN","FANG","APA","BP","SHEL","TTE","ENB",
    "HD","WMT","COST","MCD","NKE","SBUX","TGT","LOW","BKNG","ABNB",
    "TJX","ROST","DLTR","DG","YUM","CMG","DPZ","QSR",
    "GM","F","RIVN","LCID","NIO","XPEV","LI",
    "PG","KO","PEP","PM","MO","CL","EL","CHD","CLX","GIS","K",
    "GE","CAT","DE","HON","UNP","UPS","FDX","LMT","RTX","NOC",
    "GD","BA","MMM","EMR","ETN","PH","ROK","ITW","IR","DOV","WM",
    "LIN","APD","SHW","FCX","NEM","NUE","VMC","MLM","ALB","MOS",
    "NEE","DUK","SO","D","AEP","EXC","XEL","WEC","ES","ETR","AWK",
    "O","SPG","PLD","AMT","CCI","EQIX","DLR","PSA","EQR","AVB",
    "META","NFLX","DIS","CMCSA","T","VZ","TMUS","CHTR","PARA","WBD",
    "EWJ","EWG","EWQ","EWU","EWL","EWI","EWP","EWN","EWD","FXI",
    "KWEB","EWT","EWY","EWA","EWH","EWS","EPI","INDA","EWZ","EWC",
    "EWW","EZA","EEM","VEA","VWO","IEFA","IEMG","ACWI",
    "KSA","UAE","GULF","AFK","EWM",
    "BABA","JD","PDD","NTES","TCEHY","BIDU","NIO","XPEV","LI","BILI",
    "TME","IQ","HUYA","DOYU","VNET","GDS","BEKE",
    "GRAB","SEA","SHOP","MELI","NU","VALE","PBR","ITUB","BBD",
    "GLOB","VTEX","ARCO","TS","ERJ","LOMA",
    "COIN","MARA","RIOT","IBIT","GBTC","FBTC","BTCO","ARKB",
    "HUT","BITF","CLSK","CIFR","IREN","CORZ",
    "RXRX","BEAM","EDIT","CRSP","FATE","BLUE","SAGE","ACAD",
    "ALNY","IONS","EXEL","FOLD","SGEN","RARE","ARWR",
    "CLOV","HERO","OPEN","SKLZ","DKNG","PENN","BYND",
    "ACHR","JOBY","WKHS","EVGO","CHPT","BLNK","NKLA","LAZR",
]

def get_full_universe() -> List[str]:
    return list(_FULL_UNIVERSE)

CORE_UNIVERSE: List[str] = [
    "SPY","QQQ","IWM","GLD","TLT","DIA","MDY","VTI","VEA","EEM",
    "XLK","XLF","XLV","XLE","XLY","XLP","XLI","XLU","XLRE","GDX",
    "AAPL","MSFT","NVDA","GOOGL","META","AMZN","TSLA","BRK-B",
    "AMD","AVGO","ORCL","TSM","ASML","QCOM","TXN","MU",
    "JPM","BAC","GS","V","MA","C","WFC","BLK","SCHW","AXP",
    "JNJ","UNH","LLY","ABBV","PFE","MRK","TMO","DHR","ABT","AMGN",
    "XOM","CVX","COP","SLB","EOG","MPC","OXY",
    "HD","WMT","COST","MCD","NKE","SBUX","TGT","LOW","BKNG",
    "CAT","DE","HON","UNP","UPS","FDX","LMT","RTX","BA","GE",
    "NEE","DUK","LIN","FCX","NEM","PG","KO","PEP",
    "PLTR","CRWD","NET","PANW","ZS","SNOW","DDOG","CRM","ADBE","NOW",
    "COIN","MARA","RIOT","IBIT","GBTC",
    "EWJ","EWG","EWQ","EWU","FXI","EWT","EWY","EWA","EWZ","EWC",
    "BABA","JD","NIO","SHOP","MELI","NU",
]
